### PR TITLE
Fix drag and drop moving and copying files

### PR DESCRIPTION
**Pull request by AlexanderKern**
First of all thanks for this project. It saved some development time.

Whilst this fix is not necessarily a good one it works for me.

PS: It might be a good idea to publish this repository as a npm module for easier consumption.
PPS: It might be great if you could add a LICENSE file for easier understanding of the license of this Project. Stating it just in the README is not great for visibility.

Stay tuned

Cheers

### CODE REVIEW

**Comment by cubiclesoft** [comment]
I'm not sure I understand how to replicate the underlying problem that led to this pull request.  Please provide steps to replicate.  Thanks.

**Comment by BjoernAkAManf** [comment]
**Disclaimer**: I have not tested this PR.

Seems to be a browser issue, which i have reproduced in the Demo:

Firefox (Working)
FF

MS Edge (& Chrome)
Edge

**Comment by cubiclesoft** [comment]
Thank you.  I can replicate the issue.  Drag-and-drop used to work equally well across all browsers, so I'm inclined to think that Chromium changed something in its drag-n-drop implementation.  Firefox is my primary browser, so I wasn't aware of it being a Chromium-specific problem.

**Comment by cubiclesoft** [comment]
I just applied a fix that calls MoveCopyDragOverHandler() instead.  It looks like current Chromium behaves rather differently.  It no longer preserves the last dropEffect from the last dragover handler callback while Firefox does.  Firefox even preserves between multiple dragover calls while Chromium resets to 'none' every call, wasting a ton of CPU cycles to constantly update the UI with the same text over and over again.  I'm thinking this is a bug in the Chromium browser and I have no idea what the Chromium devs were thinking.  The 'dragover' event should preserve the effect across to future 'dragover' and 'drop' callbacks - otherwise, what's the point of 'dragover' other than visual eye candy?  I can think of several examples where changing that behavior breaks existing code and, at best, wastes a bunch of CPU cycles.  So the Chromium devs are wrong here.  The fix I've applied should generally work as it basically calls the dragover handler an extra time to correct a problem that shouldn't exist.

**Pull request closed without merging**
